# Generated by Django 2.2.9 on 2020-01-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200127_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
